### ISSUE TITLE
Big badass bug

### ISSUE THREAD

**Issue by Breush** [CraigFeldspar/weekendwebsite#2]
In the readme `http://localhost:8080/dist/index.html` does not seem to work:

![bug](https://user-images.githubusercontent.com/8821452/45669894-ad438b80-bb21-11e8-949b-a265a0e97572.png)

You should check https://stackoverflow.com/questions/48103939/site-cant-be-reached-chrome and learn how to code.

**Comment by CraigFeldspar** [comment]
Thanks for the tip. I looked into it, and it turns out the main developper is using currently busy developping this : 
![ingenfeld](https://user-images.githubusercontent.com/3762615/45697007-0d0f5600-bb65-11e8-8959-16b7b3195bbf.jpg)

I will try to reach him out as soon as possible for correcting this horrible mistake.
In the meantime, please go f*** yourself :)

Regards,
Support team.
